version: '3'
services:
  elastic:
    build: elastic/.
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  node:
    build: node/.
    environment:
      - extra=--reload
    depends_on:
      - elastic
    volumes:
      - ./node:/node

  nginx:
    image: nginx:alpine
    depends_on:
      - node
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80